// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // Minimal workaround: reuse Android Firebase options so Linux builds/runs
        // without crashing. For full Firebase support on Linux, re-run
        // FlutterFire CLI with a Linux target.
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr80HCwrU2DFJww0ONwucFjOypJoneiJE',
    appId: '1:1076844048183:web:2b32892d09dc0e113134b2',
    messagingSenderId: '1076844048183',
    projectId: 'did-c1213',
    authDomain: 'did-c1213.firebaseapp.com',
    storageBucket: 'did-c1213.appspot.com',
    measurementId: 'G-RX2HHW1M3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUUh85HLWsZIUSKipgJoRBkGwFYj3UNfA',
    appId: '1:1076844048183:android:ebed918ad7ac51033134b2',
    messagingSenderId: '1076844048183',
    projectId: 'did-c1213',
    storageBucket: 'did-c1213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA66TvWcj0y-kAJuLgeY-TyMaRyWwGlxvc',
    appId: '1:1076844048183:ios:2ec90d7c1dbfaca33134b2',
    messagingSenderId: '1076844048183',
    projectId: 'did-c1213',
    storageBucket: 'did-c1213.appspot.com',
    iosBundleId: 'com.example.did',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA66TvWcj0y-kAJuLgeY-TyMaRyWwGlxvc',
    appId: '1:1076844048183:ios:2ec90d7c1dbfaca33134b2',
    messagingSenderId: '1076844048183',
    projectId: 'did-c1213',
    storageBucket: 'did-c1213.appspot.com',
    iosBundleId: 'com.example.did',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr80HCwrU2DFJww0ONwucFjOypJoneiJE',
    appId: '1:1076844048183:web:eed07f9f84102f2e3134b2',
    messagingSenderId: '1076844048183',
    projectId: 'did-c1213',
    authDomain: 'did-c1213.firebaseapp.com',
    storageBucket: 'did-c1213.appspot.com',
    measurementId: 'G-K2M3C4FRZE',
  );
}
